if true then
  return {}
end
-- https://github.com/epwalsh/obsidian.nvim?tab=readme-ov-file#syntax-highlighting
-- return {
--   "epwalsh/obsidian.nvim",
--   version = "*", -- recommended, use latest release instead of latest commit
--   lazy = true,
--   -- ft = "markdown",
--   -- Replace the above line with this if you only want to load obsidian.nvim for markdown files in your vault:
--   event = {
--     -- If you want to use the home shortcut '~' here you need to call 'vim.fn.expand'.
--     -- E.g. "BufReadPre " .. vim.fn.expand "~" .. "/my-vault/*.md"
--     -- refer to `:h file-pattern` for more examples
--     "BufReadPre"
--       .. vim.fn.expand("~")
--       .. "Obsidian Vault/*.md",
--     "BufNewFile" .. vim.fn.expand("~") .. "/Documents/Obsidian Vault/*.md",
--   },
--   dependencies = {
--     -- Required.
--     "nvim-lua/plenary.nvim",
--     "hrsh7th/nvim-cmp",
--
--     -- see below for full list of optional dependencies 👇
--   },
--   opts = {
--     workspaces = {
--       {
--         name = "personal",
--         path = "~/Documents/Obsidian Vault",
--       },
--     },
--
--     -- see below for full list of options 👇
--   },
-- }
